version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./fossil:/app
    ports:
      - 8000:8000
      - 8001:8001
      - 9001:9001
    command: supervisord -c supervisord.conf
    depends_on:
      - db
  
  db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: 1234
      volumes:
        - db_data:/var/lib/postgresql/data
      ports:
        - 5432:5432

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    volumes:
      - ./fossil/static:/static
    ports:
      - 80:80
    depends_on:
      - web

volumes: 
  db_data: